MODEL_PATH = "yolo12m.pt"
# VIDEO_PATH = 0
VIDEO_PATH = "./videos/DJI_0017.MP4"
# VIDEO_PATH = "./videos/amar/DJI_0013.MP4"
BACKEND_HOST = "0.0.0.0"

USE_SORT_TRACKER = False
FILTERS_ON = False
CONSOLE_OUTPUT = True
DEVICE = "cuda"  # "cuda" or "cpu"

PERSON_CONF = 0.4
VEST_CONF = 0.4
HELMET_CONF = 0.2
BOOTS_CONF = 0.1
GLOVES_CONF = 0.1

CONFIDENCE = 0.1
IOU = 0.6
FRAME_INTERVAL = 1

DOWNSCALE = True
DOWNSCALE_SIZE = 640


# Zoom config
ZOOM_ENABLED = True
ZOOM_FACTOR = 2
ZOOM_MIN_DURATION = 2
ZOOM_PERSON_FRAME_THRESHOLD = 10
ZOOM_SIZE_MIN_THRESHOLD = 0.4
ZOOM_SIZE_MAX_THRESHOLD = 0.6
MAX_ZOOM_FACTOR = 4.0
ZOOM_STEP = 0.5
