MODEL_PATH = "yolo12n.pt"
VIDEO_PATH = "./videos/DJI_0017.MP4"
BACKEND_HOST = "http://0.0.0.0"

USE_SORT_TRACKER = False
FILTERS_ON = False
CONSOLE_OUTPUT = True

PERSON_CONF = 0.4
VEST_CONF = 0.4
HELMET_CONF = 0.2
BOOTS_CONF = 0.1
GLOVES_CONF = 0.1

CONFIDENCE = 0.1
FRAME_INTERVAL = 1


# Zoom config
ZOOM_ENABLED = True
ZOOM_FACTOR = 2
ZOOM_MIN_DURATION = 0.5
ZOOM_PERSON_FRAME_THRESHOLD = 10
ZOOM_SIZE_MIN_THRESHOLD = 0.4
ZOOM_SIZE_MAX_THRESHOLD = 0.6
MAX_ZOOM_FACTOR = 4.0
ZOOM_STEP = 0.5
